version: '3'

services:
  sonarqube:
    image: sonarqube:alpine
    restart: always
    # Traefik labels are suggested as an example for people using Traefik,
    # remove them if you are using another reverse proxy.
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${HOSTNAME}"
      traefik.port: '9000'
    # If you don't want to use a reverse proxy (not suitable for production!)
    # ports:
    #  - "9000:9000"
    volumes:
      - ./docker-volume/sonarqube/data:/opt/sonarqube/data
      - ./docker-volume/sonarqube/logs:/opt/sonarqube/logs
    environment:
      sonar.jdbc.username: ${DB_USERNAME}
      sonar.jdbc.password: ${DB_PASSWORD}
      sonar.jdbc.url: jdbc:postgresql://db:5432/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    restart: "always"
